- name: Deploying Web Server
  hosts: webserver
  tasks:
    - name: Creating directory /tmp/data
      ansible.builtin.file:
        path: /tmp/data
        state: directory
        mode: '0755'

    - name: Copy /etc/fstab into /tmp/data
      ansible.builtin.copy:
        src: /etc/fstab
        dest: /tmp/data
        mode: '0644'

    - name: Include tasks from fw.yml
      ansible.builtin.import_tasks: fw.yml

- name: Deploying Dev Server
  hosts: dev
  tasks:
    - name: Start crond service
      ansible.builtin.service:
        name: crond
        state: started

    - name: Install ftp and vsftpd
      ansible.builtin.yum:
        name:
          - ftp
          - vsftpd
        state: installed
    - name: Include tasks from fw.yml
      ansible.builtin.import_tasks: fw.yml

