- name: Deploying Web Server
  hosts: webserver
  tasks:
    - name: Creating directory /tmp/data
      file:
        path: /tmp/data
        state: directory

    - name: Copy /etc/fstab into /tmp/data
      copy:
        src: /etc/fstab
        dest: /tmp/data

    - name: Include tasks from fw.yml
      ansible.builtin.import_tasks: fw.yml

- name: Deploying dev server
  hosts: dev
  tasks:
    - name: Start crond service
      service:
        name: crond
        state: started

    - name: Install ftp vsftpd
      yum:
        name:
          - ftp
          - vsftpd
        state: installed

    - name: Include tasks from fw.yml
      ansible.builtin.import_tasks: fw.yml
