name: LAMP Deployment

on:
  workflow_dispatch:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
      - name: checkout-source
        uses: actions/checkout@v2
        
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v24.2.1
            
        with:
          targets: |
            ansible/playbook.yml
            ansible/fw.yml
            ansible/inventory.yml

            
